### ISSUE TITLE
Update tests to work with click >=8.2.0

### ISSUE THREAD

**Issue by mikemhenry** [OpenFreeEnergy/openfe#1272]
With [click 8.2](https://github.com/pallets/click/releases/tag/8.2.0) `mix_stderr` was removed as a parameter to `CliRunner`. This gives us errors like ` TypeError: CliRunner.__init__() got an unexpected keyword argument 'mix_stderr'` in our CI. 

I will pin things in #1271 to fix it for now, but we should update the tests. We should just remove that arg and check `result.stdout`, `result.stderr` and `result.output` as needed.
