### PR TITLE
bump openff-units and pint pins

### PR DESCRIPTION
**Pull request by atravitz**
I _think_ we were pinned to `openff-units==0.2.0` and `pint<0.22` because we were waiting on this: https://github.com/OpenFreeEnergy/gufe/pull/533.

Trying an unpin now to see where we're at.

Checklist
* [ ] Added a ``news`` entry

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by IAlibay** [comment]
I believe by doing this bump, we will have to fully migrate to pydantic v2+ (iirc interchange v0.4 and above is pydantic 2 only and openff-units 0.3 is does not work with pre-0.4 versions of interchange).

**Comment by IAlibay** [comment]
Regarding the mypy failures, this is what we're seeing here: https://github.com/OpenFreeEnergy/gufe/pull/533

We'll need to import Quantity directly from openff.units for typing.

**Comment by IAlibay** [comment]
For the EitherQuantity failure, the best answer will be to just directly call "from_openmm" instead. kT in ThermodynamicState should be in OpenMM units.

**Comment by atravitz** [comment]
the last nagging mypy errors are:
```
> openfe/protocols/openmm_utils/multistate_analysis.py:370: error: "type[Quantity]" has no attribute "from_list"  [attr-defined]
> openfe/protocols/openmm_rfe/equil_rfe_methods.py:261: error: "Quantity" has no attribute "u"  [attr-defined]
```

I'm going to ignore these to get this PR merged, but im curious if this is expected or fixable @mattwthompson (I see from openff-units that this inherits directly from pint and therefore might be out of your control).

File: openfe/analysis/plotting.py [hunk 1]
```diff
@@ -5,7 +5,7 @@
 from matplotlib.axes import Axes
 import numpy as np
 import numpy.typing as npt
-from openff.units import unit
+from openff.units import unit, Quantity
```
Comment (mattwthompson) [inline openfe/analysis/plotting.py]:
```suggestion
from openff.units import Quantity
```
might not need this any more, here and in some other files

Comment (mattwthompson) [inline openfe/analysis/plotting.py:8]: It shouldn't make a difference in import times in this case, but if shifting from `unit.Quantity` to `Quantity`, the `unit` namespace shouldn't be needed

File: openfe/protocols/openmm_rfe/equil_rfe_methods.py [hunk 2]
```diff
@@ -257,20 +257,20 @@ def __init__(self, **data):
             raise NotImplementedError("Can't stitch together results yet")
 
     @staticmethod
-    def compute_mean_estimate(dGs:list[unit.Quantity]):
-        u = dGs[0].u
+    def compute_mean_estimate(dGs:list[Quantity]):
+        u = dGs[0].u  # type: ignore
```
Comment (IAlibay) [inline openfe/protocols/openmm_rfe/equil_rfe_methods.py]:
```suggestion
        u = dGs[0].u 
```
Checked locally, this is uncessary

File: openfe/protocols/openmm_rfe/equil_rfe_methods.py [hunk 3]
```diff
@@ -279,15 +279,15 @@ def get_estimate(self) -> unit.Quantity:
         return self.compute_mean_estimate(dGs)
 
     @staticmethod
-    def compute_uncertainty(dGs:list[unit.Quantity]):
-        u = dGs[0].u
+    def compute_uncertainty(dGs:list[Quantity]):
+        u = dGs[0].u  # type: ignore
```
Comment (IAlibay) [inline openfe/protocols/openmm_rfe/equil_rfe_methods.py]:
```suggestion
        u = dGs[0].u
```
As above

File: openfe/protocols/openmm_rfe/equil_rfe_methods.py [hunk 4]
```diff
@@ -257,20 +257,20 @@ def __init__(self, **data):
             raise NotImplementedError("Can't stitch together results yet")
 
     @staticmethod
-    def compute_mean_estimate(dGs:list[unit.Quantity]):
-        u = dGs[0].u
+    def compute_mean_estimate(dGs:list[Quantity]):
```
Comment (IAlibay) [inline openfe/protocols/openmm_rfe/equil_rfe_methods.py]:
```suggestion
    def compute_mean_estimate(dGs:list[Quantity]) -> Quantity:
```
Whilst we're here, at least this will help folks know the expected return.

File: openfe/protocols/openmm_rfe/equil_rfe_methods.py [hunk 5]
```diff
@@ -279,15 +279,15 @@ def get_estimate(self) -> unit.Quantity:
         return self.compute_mean_estimate(dGs)
 
     @staticmethod
-    def compute_uncertainty(dGs:list[unit.Quantity]):
-        u = dGs[0].u
+    def compute_uncertainty(dGs:list[Quantity]):
```
Comment (IAlibay) [inline openfe/protocols/openmm_rfe/equil_rfe_methods.py]:
```suggestion
    def compute_uncertainty(dGs:list[Quantity]) -> Quantity:
```
As above

File: openfe/protocols/openmm_rfe/equil_rfe_methods.py [hunk 6]
```diff
@@ -279,15 +279,15 @@ def get_estimate(self) -> unit.Quantity:
...
+        u = dGs[0].u  # type: ignore
         # convert all values to units of the first value, then take average of magnitude
         # this would avoid a screwy case where each value was in different units
         vals = [dG.to(u).m for dG in dGs]
```
Comment (IAlibay) [inline openfe/protocols/openmm_rfe/equil_rfe_methods.py]:
```suggestion
        vals = np.asarray([dG.to(u).m for dG in dGs])
```
Doing this will make mypy happy and it's what happens when you call np.std internally (they use asanyarray to avoid creating an array if there's one already, but this is always a list): https://github.com/numpy/numpy/blob/1fefc5c6b767e86c2642641e7ba7a22ab0cf554b/numpy/_core/_methods.py#L152

File: openfe/protocols/openmm_rfe/equil_rfe_methods.py [hunk 7]
```diff
@@ -279,15 +279,15 @@ def get_estimate(self) -> unit.Quantity:
...
 
-        return np.std(vals) * u
+        return np.std(vals) * u  # type: ignore
```
Comment (IAlibay) [inline openfe/protocols/openmm_rfe/equil_rfe_methods.py]:
```suggestion
        return np.std(vals) * u
```
With the above fix this works fine.

File: openfe/protocols/openmm_rfe/equil_rfe_methods.py [hunk 8]
```diff
@@ -257,20 +257,20 @@ def __init__(self, **data):
             raise NotImplementedError("Can't stitch together results yet")
 
     @staticmethod
-    def compute_mean_estimate(dGs:list[unit.Quantity]):
-        u = dGs[0].u
+    def compute_mean_estimate(dGs:list[Quantity]):
+        u = dGs[0].u  # type: ignore
         # convert all values to units of the first value, then take average of magnitude
         # this would avoid a screwy case where each value was in different units
         vals = [dG.to(u).m for dG in dGs]
```
Comment (IAlibay) [inline openfe/protocols/openmm_rfe/equil_rfe_methods.py]:
```suggestion
        vals = np.asarray([dG.to(u).m for dG in dGs])
```
As with np.std, doing this will make mypy happy and it's what np.average does internally just with `asanyarray`.

File: openfe/protocols/openmm_rfe/equil_rfe_methods.py [hunk 9]
```diff
@@ -257,20 +257,20 @@ def __init__(self, **data):
...
 
-        return np.average(vals) * u
+        return np.average(vals) * u  # type: ignore
```
Comment (IAlibay) [inline openfe/protocols/openmm_rfe/equil_rfe_methods.py]:
```suggestion
        return np.average(vals) * u
```
With the above fix this works fine.

File: openfe/protocols/openmm_utils/settings_validation.py [hunk 10]
```diff
@@ -89,8 +89,8 @@ def get_simsteps(sim_length: unit.Quantity,
       The number of simulation timesteps.
     """
 
-    sim_time = round(sim_length.to('attosecond').m)
-    ts = round(timestep.to('attosecond').m)
+    sim_time = round(sim_length.to('attosecond').m)  # type: ignore
```
Comment (IAlibay) [inline openfe/protocols/openmm_utils/settings_validation.py:92]: Oddly enough, mypy does define `__round__`, so we should be able to call round on the attosecond Quantity and then call its magnitude, but something is going wrong here.

Looks like there's some stalled PRs on mypy to deal partially with this.

File: openfe/protocols/openmm_utils/multistate_analysis.py [hunk 11]
```diff
@@ -363,10 +364,10 @@ def get_forward_and_reverse_analysis(
 
         forward_reverse = {
             'fractions': np.array(fractions),
-            'forward_DGs': unit.Quantity.from_list(forward_DGs),
-            'forward_dDGs': unit.Quantity.from_list(forward_dDGs),
-            'reverse_DGs': unit.Quantity.from_list(reverse_DGs),
-            'reverse_dDGs': unit.Quantity.from_list(reverse_dDGs)
+            'forward_DGs': Quantity.from_list(forward_DGs),  # type: ignore
```
Comment (IAlibay) [inline openfe/protocols/openmm_utils/multistate_analysis.py:367]: These are all because the pyi from openff-units doesn't define the method. Manually adding it fixes the problem. Raising the issue here: https://github.com/openforcefield/openff-units/issues/127

**Review by IAlibay — CHANGES_REQUESTED** [review]
Couple of things, otherwise lgtm.

File: openfe/protocols/openmm_rfe/equil_rfe_methods.py (hunk 2 above)
Comment (atravitz) [reply openfe/protocols/openmm_rfe/equil_rfe_methods.py]: strange, this was complaining locally for me (see above) but if the CI is happy, i'm happy!

**Comment by atravitz** [comment]
thank you for the additional fixes, @IAlibay! it looks like the two remaining items are tracked in [openff ](https://github.com/openforcefield/openff-units/issues/127) and mypy, so we're good to merge here?

File: openfe/protocols/openmm_rfe/equil_rfe_methods.py [hunk 12]
```diff
@@ -257,20 +257,20 @@ def __init__(self, **data):
             raise NotImplementedError("Can't stitch together results yet")
 
     @staticmethod
-    def compute_mean_estimate(dGs:list[unit.Quantity]):
-        u = dGs[0].u
+    def compute_mean_estimate(dGs:list[Quantity]) -> Quantity:
+        u = dGs[0].u
```
Comment (IAlibay) [inline openfe/protocols/openmm_rfe/equil_rfe_methods.py]:
```suggestion
        u = dGs[0].u
```

**Review by IAlibay — APPROVED** [review]
just one spare space that needs removing
